[package]
build = 'common/build/build.rs'
edition = '2021'
name = 'ton_executor'
version = '1.16.82'

[dependencies]
failure = '0.1.6'
lazy_static = '1.4'
log = '0.4'
ton_block = { git = 'https://github.com/tonlabs/ever-block.git', tag = '1.9.104' }
ton_types = { git = 'https://github.com/tonlabs/ever-types.git', tag = '2.0.28' }
#ton_vm = { git = 'https://github.com/tonlabs/ever-vm.git', tag = '1.8.211' }
ton_vm = { path = '../ever-vm', features = ['gosh'] }

[features]
signature_with_id = [ 'ton_block/signature_with_id', 'ton_vm/signature_with_id' ]

[[bench]]
harness = false
name = 'benchmarks'

[lib]
bench = false

[profile]


